baseurl = "/"
languageCode = "en-us"
title = "Ira BlogTest"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 100
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
    weight = 10

[[menu.main]]
    name = "Post"
    url = "/post/"
    weight = 2

[[menu.main]]
    name = "Bio"
    url = "/Bio/"
    weight = 8

[[menu.main]]
    name = "Publications"
    url = "/Publications/"
    weight = 3

[[menu.main]]
    name = "Teaching"
    url = "/Teaching/"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

